### ISSUE TITLE
Echo Server的代码需要修改

### ISSUE THREAD

**Issue by jinzhongjia** [zigcc/zig-course#101]
Echo Server 代码部分有关于os的抽象部分现在可以直接使用 `zig.posix`

**Comment by jinzhongjia** [comment]
@jiacai2050 12和13下的echo server的代码关于macos部分过期了，我没找到官方把原本std.os下的darwin合并到哪里去了，新的std.posix也没有，抽空修一下这个吧

**Comment by jiacai2050** [comment]
抽空我看看
